function fig = GUIController()
screen_size = get(0,'screensize');
screen_size = screen_size(3:4);
ratio2screen = 1/5;
fig_size = screen_size * ratio2screen;
fig_pos = fig_size - (fig_size * ratio2screen);
fig_pos_siz = [fig_pos, fig_size];
fig = figure;
set(gcf, 'Position', fig_pos_siz);
fig_size_temp = get(gcf, 'Position');
fig_width = fig_size_temp(3);
fig_height = fig_size_temp(4);
division_val = 10;
dist_from_fig = 1/division_val;
dist_from_obj = 2/division_val;
num_obj = 3;
w_obj = (fig_width - 2 * dist_from_fig - dist_from_obj)/num_obj;
h_obj = (fig_height - 2 * dist_from_fig - dist_from_obj)/num_obj;

obj_pos = {[dist_from_fig dist_from_fig w_obj h_obj], ...
    [(dist_from_fig + w_obj + dist_from_obj)  dist_from_fig w_obj h_obj], ...
    [dist_from_fig  (dist_from_fig + h_obj + dist_from_obj) w_obj h_obj], ...
    [(dist_from_fig + w_obj + dist_from_obj)  (dist_from_fig + h_obj + dist_from_obj) w_obj h_obj], ...
    [(dist_from_fig + 2 * w_obj + 2 * dist_from_obj)  dist_from_fig w_obj h_obj], ...
    [dist_from_fig  (dist_from_fig + 2 * h_obj + 2 * dist_from_obj) w_obj h_obj], ...
    [(dist_from_fig + 2 * w_obj + 2 * dist_from_obj)  (dist_from_fig + h_obj + dist_from_obj) w_obj h_obj], ...
    [(dist_from_fig + w_obj + dist_from_obj)  (dist_from_fig + 2 * h_obj + 2 * dist_from_obj) w_obj h_obj], ...
    [(dist_from_fig + 2 * w_obj + 2 * dist_from_obj)  (dist_from_fig + 2 * h_obj + 2 * dist_from_obj) w_obj h_obj]};
font_size = 0.35;
txt_str = {sprintf('Pause \n Press to pause the plotting'), ...
    sprintf('Unpause \n Press to unpause the plotting'), ...
    sprintf('Start \n Press to start the plotting'), ...
    sprintf('Stop \n Press to stop the plotting')};
PauseButton = uicontrol(gcf, 'Style', 'pushbutton', 'String', 'Pause', ...
    'ForegroundColor', [0, 0.4470, 0.7410], ...
    'FontName', 'FixedWidth', ...
    'FontWeight', 'bold', ...
    'FontUnits', 'normalized', ...
    'FontSize', font_size, ...
    'Tooltip', txt_str{1}, ...
    'Position', obj_pos{4}, ...
    'CallBack', @PauseCallBack, ...
    'UserData', 0);
UnpauseButton = uicontrol(gcf, 'Style', 'pushbutton', 'String', 'Unpause', ...
    'ForegroundColor', [0.8500, 0.3250, 0.0980], ...
    'FontName', 'FixedWidth', ...
    'FontWeight', 'bold', ...
    'FontUnits', 'normalized', ...
    'FontSize', font_size, ...
    'Tooltip', txt_str{2}, ...
    'Position', obj_pos{2}, ...
    'CallBack', @UnpauseCallBack, ...
    'UserData', 0);

StartButton = uicontrol(gcf, 'Style', 'pushbutton', 'String', 'Start', ...
    'ForegroundColor', [0.4660, 0.6740, 0.1880], ...
    'FontName', 'FixedWidth', ...
    'FontWeight', 'bold', ...
    'FontUnits', 'normalized', ...
    'FontSize', font_size, ...
    'Tooltip', txt_str{3}, ...
    'Position', obj_pos{3}, ...
    'CallBack', @StartCallBack, ...
    'UserData', 0);
StopButton = uicontrol(gcf, 'Style', 'pushbutton', 'String', 'Stop', ...
    'ForegroundColor', [0.6350, 0.0780, 0.1840], ...
    'FontName', 'FixedWidth', ...
    'FontWeight', 'bold', ...
    'FontUnits', 'normalized', ...
    'FontSize', font_size, ...
    'Tooltip', txt_str{4}, ...
    'Position', obj_pos{1}, ...
    'CallBack', @StopCallBack, ...
    'UserData', 0);
PointButton = uicontrol(gcf, 'Style', 'pushbutton', 'String', 'Select Manual', ...
    'ForegroundColor', [0.4940, 0.1840, 0.5560]	, ...
    'FontName', 'FixedWidth', ...
    'FontWeight', 'bold', ...
    'FontUnits', 'normalized', ...
    'FontSize', font_size/2, ...
    'Tooltip', txt_str{4}, ...
    'Position', obj_pos{6}, ...
    'CallBack', @SelectPointsCallBack, ...
    'UserData', 0);

profiles = readProfiles('profiles.txt');
for i = 1:size(profiles,2)/2
    popup_strings{i} = sprintf('Profile %2d',i);
end
XYProfilePopup = uicontrol(gcf, 'Style', 'popupmenu', 'String', popup_strings, ...
    'ForegroundColor', [0.25, 0.25, 0.25]	, ...
    'FontName', 'FixedWidth', ...
    'FontWeight', 'bold', ...
    'FontUnits', 'normalized', ...
    'FontSize', font_size/2, ...
    'Position', obj_pos{8}, ...
    'Value', 1);
VelocityProfiles = {'polynomial2order','ramp','triangle','circle'};
VelocityProfilePopup = uicontrol(gcf, 'Style', 'popupmenu', 'String', VelocityProfiles, ...
    'ForegroundColor', [0.25, 0.25, 0.25]	, ...
    'FontName', 'FixedWidth', ...
    'FontWeight', 'bold', ...
    'FontUnits', 'normalized', ...
    'FontSize', font_size/2, ...
    'Position', obj_pos{9}, ...
    'Value', 1);

    function PauseCallBack(PushButton, EventData)
        uiwait(gcf);
    end
    function UnpauseCallBack(PushButton, EventData)
        uiresume(gcbf)
    end
    function StartCallBack(PushButton, EventData)
        idx_XYProfile  = get(XYProfilePopup,'Value');
        idx_VelocProfile  = get(VelocityProfilePopup,'Value');
        RunAll(profiles, idx_XYProfile, VelocityProfiles{idx_VelocProfile})
    end
end